apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cert-manager-config
  namespace: kube-system
spec:
  encryptedData:
    email: AgBTXR5O9u3VKQZMTX/2iHF4Rwc/TR1KRStzLmf9CqiP+I+F5l4x07BZuJV5Ir6q2sR+MAAde29+COTJyM8Eejxmuw/o6zSareF1sYOVht+UFvtiLJiPbs5BJ8U7srK37Uyv4io75oim46xBED6/yDN9AiFP/HwNgVNrBAH4fDPH2b8Ck+fLqULpVEOxD5ElM4NJBB9lfRJUkQlh6q/tewxTwMaI4InT6zu2L6m1UWFmX+MxkZ2hY3bbMJuV/kyqy4r5gBq5wkh73yFQyVLqnXdFLbWqAIclsDAO96m8GpKg1+7JsDF/u9K99QSPSrp2Eskv/5I+H7vn1MHWGlQNjPiNsW2Ma9cMIi1ohaOQk235bN9vbEHtBuqKSzybeOzjKVEWTmbPXtIvKl6rCi7NMP5Y4LctMoVnkBNOoFtaDCAtS88uweWjiW73gJtQ7t59cfxJfzRxEPtxF94DGP6XCb4h3Mqr+ygKFgf9DnuNBmVyHPLG1k04WY2oetBF+RF0txCkx/Aqz7sY6ZK2FbD0MsF+ceHFeMTWqiSDnBfH0jFmRV+9HC1jEL7zTOUXtZ3duHezhcsn9ffCQgLDg9IeK8rqMjbGcWmaVeCZ5sI/WtcACpc+K3ep7VAoKaUk5yxOncTFwAYJEMeumU+KpM0J9xgSbiHgf+c9IhhCfPYtXUS4JJbK+562EsAuBpLHjwsuj81Qwa96QRDUJjp0zMCZ55kckg2F
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: cert-manager-config
      namespace: kube-system
    type: Opaque

