apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: velero
spec:
  encryptedData:
    cloud: AgCdq6YP97IBvFiuRxJ5xqbReyB51baSSbJ9gNjp4EEWVdqD647OJfHIvx4imvmvLiHvJv7N8J3OkaZnntdFBo476Z9QjTVdwG2HYvvYf32kpHxCdjp3mWpZLtHwX/xdBumjFG43XpKo4H3gQ8wd+jDnkw6WPE/l/c/kAoxUMY1we+0CUN3Ic6xSgkGRrC6fMRQzcT3SjL2GKrU5FH7Xlh/NV5lxndONBi846lfKYNAs5tlahYbP8PuBq3U/EA1z+uhtlkQW6XV6OcOGbzGZQxE3qju6Bml+urV80ExF1HOv8mFRgMXrVgAOaR/nxHaC59jqbm+hwKeaSMDDc2DdhfQtjQcGfLlOXMLAsC2Dr5Dj2oGaCL0LyQPRwZOxEdxyY4nmcX28Xi1vT+fE392smXwbkCE+163CYU2L6CEBj/YNgZ44dBxOO35GH7sAcLj47Vz3ZSPg/JgOgZkQgxgcnoCwXdDydo/3TaYceW/2A/+57vBjqqpVp4oeSxY9pG6YChkfAjAsABCoNT0Z+07FgCORYP8vh0pIjNjWJ5oOGNv1PW10OC6WNVNap7YO6LInQxfejyShc+ie9e7GJ8JZE9BptDP7Zu//1aw0GzQpEzYggMpmSi16jNfoy8XypO1oI6OUB8XiosdiWJrzg3JXJ3NvTCRfg6YVHHzBSI0CpmQkLLBuNQ5p40QiZm8i9DkeDuLlkfcd0+mhsRJARmtuTXu/ciZX1mJImq7pslit2mA6w09vmHt2JyiK8ZCGPC23nhKqyU67OmYIA4GJERI5IRVTQaG1obKThJCg2eVRh1ih3oTLZwnF
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: velero
    type: Opaque

