apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: velero
spec:
  encryptedData:
    cloud: AgCVJJUOHB7gTyQFKyKMPxyJnN1FoSzioF2lgKv9Q6nPNxXWHGAiuWq9YgyQLObJ8xsl/fk1bjGhWDHN6jlFuo9REs3V4wfjKPrdk3ThbdEyI5ggjrg+hAXTkmnQL8JQPssM1Y7RfP5Eq5s9oJZt0/G7V0N4X4TdN18vBUd10qDNAL8vaePxx1FtGV4zkFyr4Q60nP28QbGFtLgGperN2jQaxdXiNk7gF4V7bc3i90hPV45NTzGMizlDmwOzrsDcpIM4C4pVhtkjzKOG7r9IyGp2ZcpF3xyIpYftNnfKJXjp/gzltQi3wqOPlnYvYYLGZ7A0nIzJzjzuYz++AsZju/i+x5bIJuGIWCykYAiRRozqcmNxok39p3XG2Q3T66URVQkFMfQp/rICDiFXSJ5h2r+/AyLTCJ0mA6cxpYFvGYViF2ztd9ARGSqguUvOh2zo3D+1OZ4hgQ7AKg4cOjoIfHRoD3QL73bPLjH3qVaa27wT5IsnOvGc068477Q4MF2cqRH8vt1ikOHDagkOGRn3gHzV669eZzw6M1Lgm4V9FnA0lapTkV0oY2bpj3lGB6osx6juJ2MZ5f0kkr7k03eY1a7+SbWo4Ldy0i2TYQ4JjDWgNfRVMufY84lIzmLVmnmzPP80JvuFNulsYYK9K6NP4FVzUBTV5kNTjemAdDH8dCBCE5I7ORO8jAFxBqVea1LwcewGt1pMN286AZclxXQEgPNM10t+Xy8sMVEDMSmr5n1GLTfAo2hL3NO1fOJxjucOOkqtJCKYLoM+sp4ms3jOgx15S9/d/w4hCwZohR16wC78F+OfopOf
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: velero
    type: Opaque

