apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: diun
  namespace: diun
spec:
  encryptedData:
    DIUN_NOTIF_DISCORD_WEBHOOKURL: AgCbbYlasFi8KJEoBkMIu45cxLw0pagRZwQPIhsdOsa+zOgxyjHph3p2k5d8FXTkDXmORrCe2J1rCnJcHRg95lzbAhKWD7eec/Xc9ZmqghiVygU/dZ1ovy+hEt5cyLD8aS98x+jDIonChJ1vPxUxbnCI3ZFadkTn/+fK5HKPV8a9jkNrPCwRoXJR87CxPLj2zqusuqZ6cO16VQux221cq5JzifglRtk+OxVul5k40Y9z9WGxs4Xq9/8O4RkljrowqUC1QgWNLbJ4R5OBunHAYkV7roQiA64pHHyCF09pru+ou7i1xlL+iyvVV+ihWLf3WjEIntnK6ZgZqPqMg9+NiC4vbLwxJww6DOgghdyyNEV1iymX7+IuGFjwdI9rzH5ub422tqCtxPGnJcJDGbOibVtMoHmkkCpn5q2t+15WEV+T1qOibWSRi6HRgwC+GDo1GuMTefIQQvpMtIFgmkUAgTZygtzQOcg6qkZUzK+8KOsdK+qS7OqcACrpjhFDPDocAwOg56IEgYQmY9wV3X01gBQm2JRB13v+xR9K2sjUtB8IkUzoPxZ5kE7OWW3qequ/Sh8qD2z8bmqBENpg9YLtmBTV4EtN2pzteqcuULph6qisO23pyjQfgl3j0E4e/GQNllnUPNGFbqkfU39rrJxT2VOXxYK1rIy8vrW9UKcgQ1d/+nK5TqDyeTayE+ZYp2pbXljTL7UVIGjajbTS8nzLe1Xyx18HgQhlOqOFYsTRaCk4BFHwXAN6UNb83D8IyffrlOcHvYih2XBk2Qu11iib4vK4HTvSpKaeR5I2IATOzIcu2sEwCr7IYXHLed/pSvHkcrOahEwboaDcsNhN5rIa8vUhxuT3rivICOI=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: diun
      namespace: diun
    type: Opaque

