apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: config
  namespace: applications
spec:
  encryptedData:
    DATABASE_URL: AgAOGguTKlwONJl+O5ZkDSXPDaRWh/uaSfWSMAtSSODUoKOkUP+VQdm5sgatR/PEiBbhYVmrbt7R/KJHXdCUogOOcWx61fuNdhUslb7KY0UhmSCZFiC7zTI27AKCqVgAY+mxkv+shGrEqXPk9UwpRy8M0Rhyw5b/KRszFTf+xPtvww69GDgriQIQhNWsJ2I2Q3tYxWET97I5EFWf3dkmmGKMZ9wsuUpirKNRPCKsiEVwYgq1jNjKufbwhhdd0j4ci9jmop98yA9s8LOTmWm/8FHHblClnDqosCTufqCFGmDzaQAPj6bc8iiP+5LEcD6CVvm1yZT3DIf5IKX42aF6q2bg+SWXrpqFDEbpeVFLMZGKCZ6nHQO07w+9NFAPjTHI5Jtu2CAJxvy2k0rpS/XqXX678Ye6mPJ4ycYMWb7Ila6p+RMd7lyaqRjbH5LVLs8wMt39wn/zD1d6TrZkUjupNQ0zpD5xGz60zT4NkB1PDUdym/bHkICzKSbiQuzas7HP1xa+Q1jUPTjH0LEd6iVr9+sMmyeBDPiMkvNcBF4O+vzNuZfxvatxpfV0Ya5lRa6i5gacjk35f6vx5lWid495zhcQQCzSDNdULSUgHr1WyVnP2Xd/qVrQiSLnAfm9c6YfRxkKAQMjgUanMNFMHmoRAAkg1SpRMttaBuHsEcxw6sKlcWiiWaI1ZpXFEspvwjYzMBD+U1UhN/iqPoI9fJjdZkszFVZIMEYyXVQw98n1bBtCZKFoHiodMnh22BE8dwWmbGgLMJm5zYTDu+BUSkvITHMq/HozLVfmd8n07x/m5LT9OwNwEYtSB7UhoFkBxJLH
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: config
      namespace: applications
    type: Opaque

