apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitea-database-env-secret
  namespace: applications
spec:
  encryptedData:
    database: AgC24+dMCIdQg7g5eepYirQkuZnAzZCItVYoAHJjJE8h1/9furU7rqXuphiB4SezwUIiqcYHAxNIzZs3Q74itEI53F6TnjK7bg4AOIh6ibiy2kVrpOcFsVQSwmr1tgLtZdYyGmjBsfzL1rkQscRaTLBvSXZORSoNJLZWOurMnr3OheT8B8K8W5bL7K4DXigTBhly09nA8kiA0JacFRkm90h2rQG3nzPbNrfb4B0mbCByBotKMpYt9Z3NpolbG/A/UyxQcOBedavYSs/a6WW5iRhsE5WOFyyLtRLxffyvVocl5AE9Fqop/E+WWKn5UeScNI9qnZLgsxpSXSLldY05lO8gCTI2qZ+Mj9YPdtbBFlDfHTPcUYOwCUwcVYMyCYvpQv0/EXQtNhDsaf9+nrM8Ml+eGVMXD5rZKX4EEBEU3dsJCrAbk8H1pTwTk2JOXgnwTx2qw4h6sWjahhWoKpU2Bg+Oj6vh44IS0I50QvncDakS0uSx/P5pVg4uS/lTl5v0BVQ3phBWX4h+WcdrbrkehHtgGNfsfLuxc5ycmpbXfOSo6VLasE3zbGEINWjVSwiGb0LPzTO/HNIZVnnaxB0W2FEUb/U96WvxlTJQh9iAy8z1RL4mPgojxWn3ZRoZo5Mn9vhnlCFLd7pZbl/mpJo+8m+Pb7zVcndfDySST5evMUXkeXBxqwEX+JLYHUpZYUOx06/ptnoKcn3O12iqdicc8d9O5Ae8Qshc8/Tg2jBnn6HuYhVl0te+vLQmiuF+soHYNovuCDokxhpmoactrRZem/zMxUBqFg3aHlGRVUSzbYWs+wJYBIjkf3agwtkA0LTJf/4pB7Jom8wDpc6eC69R8I0tcIy3pkT6zw==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: gitea-database-env-secret
      namespace: applications
    type: Opaque

