apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: config
  namespace: applications
spec:
  encryptedData:
    DATABASE_URL: AgC7P3c7iekt/GqeuHP2xc7zZOin7lVE43f8vojsWQDW4v6OogyqxrXHT39iG7OSAVtXraO1p6cXQNJ+k0kRiK1LWzKp39ifRCu8qM3EEJDqB2CwMFRbUhdJ/nN1wCV+e2ycNKynRQ7zH/0R4IHFDXUlhZeBX8B7Uh4RPM1TRGWq+A43hBLrzEmi1P/ZcyBGlbnRPjUnHs9qpfmfLm8r5m6aPDigznTgtwjj022UShIbM3RR3YbKV8rt6Pyq0pTxrXGRXdlgvofBDbYxfjfc5wvESPOxXdi1TJFcGcguOpTr/RIxWBPbpn3csdzvmn9Q9LVwaSYt3vIU2Jx/s7U5Vxm7GTr0kMJEvznY5eP2FKv0cc3mKLSRNHrCNAC0K1IsB9298tiGQekvKFGwxmSfCsZvgNWgyLAJisXhZVyUjL5Emg1SZB/OH7M2oe/ICGQEWVkmuwdgEaFgS2v4u+DilrvA4kU+d5Y8hDncL6cQLdZPNpNHH3Urc7XtTHukcQSrO95VwUw50U0ust2VDy44oayl+SIihdE93l1+7/ROGYoUTY4Alp9mKY4toBAY396/TbMuDLV2dhFhz4/uenK5wjv0U2szQn8t+5ERmyszIIIs7P5rKBzL5nM47rxvj/jWm2QNME+fQh8KthsWInMCxs/fY+oFtAzS9aDtT5+Y8lKvAfl5UlMZcUKFkowbxzVMvEO8zB2i87LtwVmbHl+ohHz2IMWi0utrGwjfVYgJQ7oFu1iSmD4MYv8ukfV69ED7nZjdm4y+djMXr4c6V7Nbe/EvMN/F21vNFQtkJTf4EbHQp3y6hLiiufzVcZ8uRz3H
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: config
      namespace: applications
    type: Opaque

