apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitea-admin-secret
  namespace: applications
spec:
  encryptedData:
    password: AgCbJwyxLi5GnWt8hVTzelW8vv3F3vkOrcM0j7NIsAm+u8U12JeWj/vt/0ZgfLZE9/EXv49em7uKOiDlOM/Tktb2FP8RKtyYYKZTeL34tjh9ELrG6mtEG+Yu1Bz7CUNTQmaM22JwAzUL49Lg+REaUT1OotdDnM4Z+Uu+PpRjhR9E1YMdVpGFPvOb33Wlnb4NIZHwkLVLGdfFGvlAsmmh5aZLsPtICoxrOXt4EOLdFRFwjYJxYalfYdSLmywOI49eTqrj5r34GRGmf7ZBI2ylPTySn8tx9ecrz0x33nnxHWbxK001aIRsuz0OeXgYaHWgfoZMS56L5jafbNsEx6rjh6jjjrKzNqWF9DZlWD608vp4MeALV0RjlevBLO3kvq5WyBRJkksUC7GPV9Tr3Hoc/QSzm06J0vW99qhaK8+ZFk+2YSCngDZu2u9WXZzVFO4g9BTlxi0hbl5E6J6RsxMgP+QwH7boEltx3DqiCU8zrY21/DkscVJmUroVKOorgY/t36o6B5Rg0YenhkjJ/e1Cz2AZeK47IMDy8RIbimiNJw+OB98N3yR6fubtlNkFteecnOLE33o56Aju1dlq52zd9T2vfFMnvZRqI+d5ipEr38CM/8Peq0w3WDOUEW8sGnRtP6l4QkUOtYj8ogpISJiG3FW76WPKyoLPvcb4fxuJBVLBH6P8M5fSqzLHcDH5ybdO8hTK4wWQaPBa6j0eY4OVYa+OkwdLPDoT7h0=
    username: AgCXdeLH8wVpotXbUMC3VJi9FU6+NNmZ1MyNkGNV/312CUJo4ZGLVbvQPQtIgiSCqQ57N7TVOA3pWnkF8+X5AGJV/3JJUyjUWgl8H6iZfn+05jWTNI/qpvbwQ2fPZYZuCkHFopBTgcRWuNXR7svB8qKOi+POepoABYeuP6v69D7GqXGKAFjPn6u/xoINIFJn8qfB5IVIbaneXJx9YlFaPPLJNapaJd9LelIdGmQJpsXw9s+guSNMlCPURtTwLz9bzF7nkETLSmdxaBB3Lj3HK6L2BdPNY5+pZmIESl/iDWiltkjr5S/eFTHX3LKH2SQuIqq1Viv3cnNf2WVQqUUnRdacic85IQpVBD4qU37hI8Wy3Ooj6sFYgmjOF83qvshivFodr4+1Thm6cNODnyPhEN0WjwlDh6duPwZfm7BczitEylm21i8Ca4PQlhkenbu7QKr1txG2QzDffiXAHty0UtiaknlFnPmZaGTZbvY2i+Tr+kmOvXt6i8AUAvH4H7VZbV/WMkCGbD4Ca2riho93QJSNfL+Ke7iM2tFqGA+uSVme8ZB81m+LgNkeEmVAVnlLRXwNtEAhRdzUeo7lLMn0JxmScCEz2PzE5+96RRj7Ot516gviNOJcOitNBAJATUdINuJHVvzif0T6ov4lq/h9TWLHFfuweD104ApiN2BcYKPDwi6wZuHa+qVRni88wkXgQOdijP8fq4IBAcs=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: gitea-admin-secret
      namespace: applications
    type: Opaque

