apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysql-credentials-secret
  namespace: database
spec:
  encryptedData:
    root-password: AgCDsz/IHWlmQmN62DZKmM140clSwzkcWP5sk2ZPtTA+dLLpfHWZivYrAYwSpTmrK4HW9XuODuQxfmrt2hAc0kj0cRIvWyZuramSPV40mWZo1UbcerbBZoAx8HYPeWlcNglctj31+jIpgpMCJFlvejisRdVlf+EUUcK9/YgUopW3Civ18gekjKYjuMSovZUeWC6LIQYa6LnrXMgN2uw8wTk1PyfylLZyK4yBhEMk90j5RHk6eIayUemSoSIbISZ1eGdM8CAte45m4SKn4vw0C2olzp3miM5coIfYibNq0YUYayOiBL1g40+RsXuM5PgbVcCxxycs/KUaw+shAh7gvqaN437FrnoT6Pxb8hG1N/LvJfoTAkjOJELafUdb2lK4xIToHx5Wl1DHpWxiRWNJpbl21tlE9TFVbFos9fFqLIN/Y2qpgxPMUps23AXYU+ls9CBUd0E+M1zNIav9Q8EtsFrWZIJmytf54klRnM87N63q8m8OWQSCmsSl30Oau8HKemEUhHD6Eri4Used0X4giCu6D2UzFz4G57PRH0fsmnUJ+o0+3IoHoWboYJ9K3cIXrTwJFcV+KWOCPeie1Ro004l/sVH0wqUYKZkr5XzD1VuXcYWOLBgN9/L6doZE+4v0ycg/0BocbE363S5vDessv1FF05lahXrXnqLtgsrfkFGBWKH7o9Ejb+NNaUH/z6EG555ZmFMDJYSM4p4vIqvaO1Bx97Kb0spur8A=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: mysql-credentials-secret
      namespace: database
    type: Opaque

