apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: config
  namespace: vaultwarden
spec:
  encryptedData:
    DATABASE_URL: AgBlB52ZmULiDAVq5lNlZnGxNO6ueSpxAJgu5kbOFax7LuzMXinMDHCvmx+NfEDnMLtthgfcjbSPm0JFULD5p2GKCBNkC+IbuTk/FGufo3iSchGRUC5iRTck07G133HXjooA1SJ7fXdiXC/0GOJtMS3svHfmk9dOoYa5L1+VkrryJX3NNw1/iOOqqAWlH/F9X8SnzFDTxSxD790kicIe2ASHewRXAmFmNMua3L1vNxImAbTK8ZELcvV26n/AS/PbFchut4ZSmEFTbC2qLXYN5kukFDlQ8dJqJZMdQeq4bqN6pFFMurrd+OHofTmT/xi5ZJAbIZ5XGhIqcJt4A7ClAF4kYVWtjGymPmLhG//bcGF97gHX8dkisE5/KYAvKYdr4mVs3MgMWDXRvDboaSqpXbxO4rzw5zy34Svqq8bTWCfcs4eEMiq3MNL8+/OYBSufpykBndyO+dkA35AFcwpjCmMQxflsFIzWJdcOCJgWFjIRh0YDGHVkv6H6ZO1NxgR6HSTYShv4F0FC/1E+tEPB6awet7aD9Ecq4t4dVNKJOsV52AH6FpXzTnV44anCeP0cUIHjWC63MiKNzeViRdgVTmcNN0OUmW6gnt5Pc4IEFMo+9bfIR7eYGrbpNKCRYtILrUiwFOGx1s9bslkA8pEeug2w9QjceGURyEDURGxHN/LELS6NBn7tLWGWgHIH3eiwP6hGmqc9zm1fy2o5jCbyo1V3NxxnHzknC6c/XNW8LmQHrDk9Ls4AmlkjOrlTSGkG0obZA2LZk9OTQHzLqXhNm6gbkvHZl8q6azZeAg3Pe7amnAQI7oKw1GTYFHUvmKGUb/LFxA==
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: config
      namespace: vaultwarden
    type: Opaque

