apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-cd
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ''
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://argoproj.github.io/argo-helm'
    targetRevision: 3.32.1
    chart: argo-cd
    helm:
      parameters:
        - name: dex.enabled
          value: 'false'
        - name: server.ingress.enabled
          value: 'true'
        - name: server.ingress.ingressClassName
          value: 'nginx'
        - name: server.ingress.paths[0]
          value: '/argocd'
        - name: server.ingress.https
          value: 'false'
      values: |
        server:
          ingress:
            annotations:
              nginx.ingress.kubernetes.io/cors-allow-headers: "X-Forwarded-For"
            hosts:
            - "apps.gensokyo-cluster.lan"
          extraArgs:
          - --insecure
          - --rootpath
          - /argocd
          - --basehref
          - /argocd
        
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
