---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    name: ''
    namespace: ingress-nginx
    server: 'https://kubernetes.default.svc'
  source:
    path: ''
    repoURL: 'https://kubernetes.github.io/ingress-nginx'
    targetRevision: 4.0.16
    chart: ingress-nginx
    helm:
      values: |
        controller:
          config:
            http-snippet: 'proxy_cache_path /tmp/nginx_images_cache
                                            levels=1:2
                                            keys_zone=images-cache:10m
                                            max_size=1g
                                            inactive=60m
                                            use_temp_path=off;'
          service:
            annotations:
              metallb.universe.tf/address-pool: pool_ingress
  project: default
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: false
