apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: intel-gpu-plugins
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: common-daemons
    server: 'https://kubernetes.default.svc'
  source:
    path: deployments/gpu_plugin/overlays/nfd_labeled_nodes
    repoURL: 'https://github.com/intel/intel-device-plugins-for-kubernetes.git'
    targetRevision: HEAD
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
