---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets-controller
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: kube-system
  project: default
  source:
    chart: sealed-secrets
    repoURL: 'https://bitnami-labs.github.io/sealed-secrets'
    targetRevision: 2.1.6
    helm:
      parameters:
      - name: commandArgs[0]
        value: "--update-status"
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
