apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://charts.jetstack.io'
    targetRevision: 1.7.0
    helm:
      parameters:
      - name: installCRDs
        value: 'true'
      - name: prometheus.enabled
        value: 'false'
    chart: cert-manager
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: common-networking
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true

