apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mysql
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://charts.bitnami.com/bitnami'
    targetRevision: 8.8.27
    helm:
      values: |-
        global:
          storageClass: gensokyo-mayastor-singleton
        auth:
          existingSecret: mysql-auth-secret
        initdbScripts:
            init_gitea.sh: |
              #!/bin/sh
              if [[ $(hostname) == *mysql-0* ]]; then
                echo "Master node"
                ROOT_PASSWORD=$(cat /srv/secrets/root-password)
                
                GITEA_DB_NAME=$(cat /srv/secrets/gitea/db-name)
                GITEA_USERNAME=$(cat /srv/secrets/gitea/username)
                GITEA_PASSWORD=$(cat /srv/secrets/gitea/password)

                mysql -P 3304 -uroot -p"$ROOT_PASSWORD" -e "show databases;";
                mysql -P 3304 -uroot -p"$ROOT_PASSWORD" -e \
                  "create database if not exists $GITEA_DB_NAME character set 'utf8mb4' collate 'utf8mb4_unicode_ci';";
                mysql -P 3304 -uroot -p"$ROOT_PASSWORD" -e \
                  "create user if not exists $GITEA_USERNAME@'%' identified by '$GITEA_PASSWORD'; \
                   grant all privileges on $GITEA_DB_NAME.* to $GITEA_USERNAME@'%';";
                mysql -P 3304 -uroot -p"$ROOT_PASSWORD" -e "flush privileges;";
              else
                echo "No master node"
              fi
        primary:
          extraVolumes:
          - name: mysql-credentials
            secret:
              secretName: mysql-credential-files-secret
              optional: false
              defaultMode: 0600
          - name: gitea-credentials
            secret:
              secretName: gitea-credential-files-secret
              optional: false
              defaultMode: 0600

          extraVolumeMounts:
          - name: mysql-credentials
            mountPath: "/srv/secrets"
            readOnly: true
          - name: gitea-credentials
            mountPath: "/srv/secrets/gitea"
            readOnly: true
    chart: mysql

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: database
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
    syncOptions:
    - CreateNamespace=true

