apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-snapshotter-controller
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/kubernetes-csi/external-snapshotter.git'
    path: deploy/kubernetes/snapshot-controller
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: operations
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
    syncOptions:
    - CreateNamespace=true
