apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vaultwarden
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://k8s-at-home.com/charts/'
    targetRevision: 4.0.0
    helm:
      values: |-
        env:
        - name: SIGNUPS_ALLOWED
          value: 'false'
        - name: DOMAIN
          value: 'https://vaultwarden.jlgs.me'
        envFrom:
        - secretRef:
            name: admin-token-secret
        persistence:
          config:
            enabled: true
            storageClass: gensokyo-mayastor-singleton
        ingress:
          main:
            enabled: true
            ingressClassName: nginx
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-production
            tls:
            - hosts:
              - vaultwarden.jlgs.me
              secretName: vaultwarden-cert
            hosts:
            - host: vaultwarden.jlgs.me
              paths:
              - path: /
                pathType: Prefix
                service:
                  port: 80
              - path: /notifications/hub/negotiate
                pathType: Prefix
                service:
                  port: 80
              - path: /notifications/hub
                pathType: Prefix
                service:
                  port: 3012
    chart: vaultwarden

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: staging-apps
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true

