apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: democratic-csi
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://democratic-csi.github.io/charts/'
    targetRevision: 0.11.1
    helm:
      values: |-
        csiDriver:
          name: "org.democratic-csi.nfs"
        storageClasses:
        - name: freenas-nfs-csi
          defaultClass: false
          reclaimPolicy: Delete
          volumeBindingMode: Immediate
          allowVolumeExpansion: true
          parameters:
            fsType: nfs

          mountOptions:
          - noatime
          - nfsvers=4
          secrets:
            provisioner-secret:
            controller-publish-secret:
            node-stage-secret:
            node-publish-secret:
            controller-expand-secret:

        volumeSnapshotClasses:
        - name: freenas-nfs-csi

        driver:
          existingConfigSecret: democratic-csi-config-secret
          config:
            driver: freenas-nfs

    chart: democratic-csi

  destination:
    server: 'https://kubernetes.default.svc'
    namespace: operations
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
    syncOptions:
    - CreateNamespace=true

