apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: velero
spec:
  encryptedData:
    cloud: AgDTApir9tp4j0M2PyztvGstx9uR+yy3LKVLyysLgdzXREb1ocF2TG9ekLldq/XF1kXqMOKLdbnZi+76/yEREG9i8ftJENdYOQVdoRwysVPTlIDwEcr0YsgU5OgBk1rZnwxRzACcxWktyYLK4vO86CiezOub+LMUrKdW90vif4NlL8cPnvVsIRYIMYkWORdxUwaqUaSZebOF2AEIyIm+rVPkeIBCWH5N0YUoO9wQlJhg3oCqgiPe+MHDfBmcQcV0J/sEpKoSeQ5/H1cxSQm5vItYps81c5+mcZ887XV4SgeSA7adYLBtyqHRKOh2ifxFIQI0MW3e92SLb6K6f70I3yLH1h/UzbSRu4vluR7q6FNtFgF6ukHy6XTRZV4jrhbMsxyIgAtKfDe78o6wZnC36kfABOd/pQqt6MZgiEkvyhJR8Hi8gAFndNWpdzjeho3xXGINYpUhufTbSV7WkPgVCPMUTLBz7nwOnN71O20V3YJ3sDA4Hxz2i3nrUFNSFfK/coc1A5HuYwUo0n9dU7HAQzbWdoi13xe2ugYFXm+eE9BnrpbFrHYy5Z0zPXVHBBi1WEVJUBZ21j8VsYthH5CHaIUFTU5RpGS6KO6oB/hgCk8r8nYyvZHOPQQF5qtmYXoj2sqG8ZsgBMBpsbFMELg2s+XC+kPPX4RBRIOGgiCemUsHO3Pyu02Y+51ia2q1LaIg8cDU7pD3vnvzAZ98rKisQDV4xDhT+c+z+KvJqpR3nrHTKe5G7XNEXUwBpccYG9YjF+gzhf3Y8on7lncER9bvuKVVNAF9ph42zqUCfAgKd5JGVQ1pixaD
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: velero
    type: Opaque

