apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: velero
spec:
  encryptedData:
    cloud: AgCtb8z5TZCR8EViGwMyXXrdtSeNkb7Zgn+qWxSPizGtnE2E7Qy4jW00S8BAmo1AXGn6zFA9JVzg8ERKVKR3mT/CgzvJlvM3TYjENibxE116o9sBj6tuvSOt7kqe91h3AMHa3cB9KjgyjKbGjJNajTHxEa5sfSw404Mq4nIby8+A+/i8q9X/HZrKkClBy+gTMmuUVNsrh5YubR8djV/+fwD2OplalWDT1w5qg7Y9gq2bUM80AEiTv1m8gAOrmJQaiBda7CVWqZk+RxVIii1RXDAhT0KQshPf0IQ/qZcbgIL6QfXBndyal82wkIK2BFzkx9dp81TIXFneY0UMidcHjGo94AvI1ae/KWirK9VNmlSKDr8kXEPCwsNFy4eMMb2pIsWW7RqNM5maHFrt6y5g3CMmF0/NbTpfNxHkdaDCvm2Kg+8XERJZur7L+GUTN7Ux0IGUSL9JKX7qxtzOOS7ORI/lqSL4ZWXjSQOHL8wpi4rFerwv+AGx9ACBWUhiofTO6vy62lcw+zEDZuPWQuOr3yGvk4vBHhJKhCnuapoSJdNTOZF3XXdA1dGGjEFHXTYcGf26oaCtbfb3BZj4MTZ1cJFV4MXipMPEqg43vGPUhUizlQnM+/f4tb3BcP5aQzHopovf7eE3t3gxasNgbry7G387Dr6lqb9FMxAKhnJSaNrGZegn1zHVXKpOICLYA1DNcexO8ysOcqNhw6C5IFtvVu6f/evQTl8fagtCn0KjNy/ESdrOk+YtcOhebWwb+OTntCIlp/l97sfWFGkixbRECxDG3T6tAagv3iXX12Lsj6NphSMBZrAo
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: velero
    type: Opaque

