apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: cloud-credentials
  namespace: velero
spec:
  encryptedData:
    cloud: AgA3fXJJHN0Fupjrhj48V5ILEPoS30dDdpOO987H+pveWePrg4+e3QTeZ9IKrZxAGD07BeX8fyjtWJ9hbfCOfP8sFRl4spd6+Jlzvo9Gc73u5i7gLoxkfYDOP+brc99iFVZo28FnqRvm+4QPhfQjtVwB0Spj7b1e0+kQMptUDHyBypPKDQ91HaRbLI7tTtk6hVwzcoW2bI0Mh64S63DqujNx4EYEFwTNRCj59sbfCTrbIz0DcvEagKdPfyk+GLnFc5k1cFSL7bdD8xY+WB2F0qX+j0BXrud7yzTppCLT7aEWFlTvsp9b8YEkJT4q+BVhdZHaB+VMIpCs2+0N98NMX9jcDSMovUobUC1pkAiaNjZTkzDbMlDOuKAlLYinKfLopNTd/NycD2tx1hx7+/C6hHpio7uh0wiSwnvOXEz0si34pp9HFb0SFK572FaH4/oAxi6gY+3IPXV+0uRbpfUN3x+tIJw0O5tgCuajVNQ84Q6ZqqPyXXM2NrRuT8FTs1HjjJZUj2yw3YJP3NmXiZ6KUmLA4fGrzZwQLGITg+eRFEhOsWKARv9ZeXF8UPkBUPyppUG0xvOuE2VlVD/jjWid44XMRUtwHLOQAX/82xSvEJKr9GYBHN24JvUQSQmZTI/QRb4N7z76mLNj+J2z5UVsFQ1pWC3aG29ZurnJNEmr8wg81EJXFnMgeEktxtA0Fi8oic0yT1spsBZESfM2PBhXVIvC5Oybp6ZLFXIiBxeab1gdCtRsZiVPHJFSfe5TOWub3JSooTB8FLb4nrM8xwcivCnXPPYoN8j0JUzM
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: cloud-credentials
      namespace: velero
    type: Opaque

