apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitea-database-secret
  namespace: gitea
spec:
  encryptedData:
    database: AgAKYGdu8UVAiu5eZXau/8FvaZPdXX9umHZWIRIFLHOhvfvFZSUJU+H3oPN4fOm8HfaNWLLsNA8BOOExLH5awS8R+P25xRXGv3Xl/w3oc99UsoUy23O8hVdFMz2R3/n6WXKbtD5obTpvScG+FqY4nL3C/jbiCxyg1RFL08AuQCvPSbLub7lbVjmYC9BNpkXNAjbN+9LeBElR2Pf1GlUau49XbaYffbbKLg6JJhJrkMtzELAP+PR709pZ7hurHHNiAXj8VaLSwy9B0mDJboWU42FSMLz+Zn9pq5vWbyg4xw81H4Z9SKnoeH54d5ie7xqC0db6V5XsXwRaMhn3hbedbKEO1Px5k2pDMPDlLxglRd4qYXGr3V9oeiLs1M0zrJWkDLbh5hFePlZEkPdwCiB8hsEZ3BevL0LDUoVDRDb7ApqZS/X1sVBH82gvB1bqXwjnzoBJAcztCvozxhByxUq2Hac9tXiVTeced4n/bX6my1jtpQ7BMJSMGsjhkd91r6PmUKpT79nGde4ZGSZPjkzDgWzgwr0NTEHJhl2176V6kYhSWCFuV0SeikuPNJeSC2xloLvfQ7ISOWC5VL4y1+f/flDKjCYNNeN3EaC40Zw+Ki57N756rh7+N+Vw2R+y61bF3x7hxwmPZOU324JZMrJvPQNH6efqP/ttVKBzrQOWmoIuG1KrIFZnCz3PrU8hKhaqkWwv7YBLu4YQhnIpQyeaRfQnsSUj8kdYdUQ0IhkG/kRZTlhVaFmAaRwx1mB3DA+Oe/T62ZLcqV0aDaONAyCdSPUE74LfMq+1W+aMi8kHAnGZgC0mdq3s0aBN3DQpZN3gRUSkbfiaSPl/Gfl+rNoq0dp7hp34JSis
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: gitea-database-secret
      namespace: gitea
    type: Opaque

