apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitea-admin-secret
  namespace: gitea
spec:
  encryptedData:
    password: AgCGwVnEnA5thVCzvgNPy3wpFaLnRUOZ592r5D5FCzd9mGHsbGAWcNYEQn4hIVC6n6YbsO5b31LoseE5QmKWpG9kqhU+7WsJXXnYHfdJz29yfDPweF8k4qdGLCfNSnNM6cmbAu7SnNaM+229tgmOaCSmM5tNd0Ultjai/ZemDFyxt49OQm/iaysXGgqApqj5FbL2E94x1vgH9wkKCMUCs5uI8Cu8fy2G9caWlh8i5CloVliqvkqTWz88V1xSzQF2WZnDDzJWaeGPoeCaNv5aOFY8d5zqzjiX3u31WQTy1j0YWpF/wQJoO05u4GoHcRhuHZANFGjBT1OSgdvdK+iCMvLazmzvLxNP8AlezLHzKWdHjWkvp2FagsyZADgQJuRsU9O/XMm0R+8kHU2uwYeTZCtxIKXf/jtBk9Yrir/ronLctOSzx8l47wo1c6s2CpOFJ5bcNchKOuDJCQZza+n299AR5nW5Gz8AyaG7F5POjan5AcwKGv2HvHK7MbPQy9eAbVxKl/tCKaz5xsrOv2GcommFWcbly1PS7TTOcGovg99kLI1Ko6GQZXbDblcfuN1oS0WJDU3it8RCoscA1+YuR3JsZiJpFAmnsVTSAkmtB3IuhmbF/2nbX0DcElDLJU1HXEJpaj3YpRtaymmrmBNMuaIP5bblFLnoHCVDsm0yKb+dvdx6Qb0aX4Hr8asmCBKFXQjCBb1RVmEEcCrs3DpTQHQfcmks4ZP/cYI=
    username: AgA9wb6wQmrAkcsZoN5wE+COvyMRtvPQWHFxLSToKkxyE73a7phnwo98mAkFfHBzDyCJg7KsliBg8tJvm7ErWU7udji0h46UfPEdHAk3cFMVHGfXjYoB0/KsCHCd1nuWAFVxRWfzUX2zalt7ITQY2BGxP9ngrGEF2y0Pemh7khabpSeLOkIlFsT3UCyD/Ft1s3HR1H2j4okgiqQogjQ0WRmG9l/agG7hmarGORKR7iM8N7IFpZYokP9Bcp3wz94hdoAtHvTZwEYIf75v3lsJM9O+sOpNORhe2l5yBaqI3kQtQTm4ACVIDvHrJQaEY2aXccyxnk2imDsFDNsHUyT/PxPL7N4yl8aVrouhVQ1kuTK7yetVGSnrYh0WdjJNfqjoOeWdfHqirDW13/JHpYxgrKdNnVX24W8lGDwK0GcF1bJ737xCGauG4Ykk3PqEpdUiWlYF9IlqfPTNYSGBOTFonTwnuixRQQ+7JxKqTweX4aNxxgCxCclFK36M/sDbUTpSJO+L83B2kp/ur4k9a62XSRA/KH+n/7t+L0jRWk6NliGlir4sOvoV1K/WlaS1nefDWHaRhg+Ke1Xf5LhraBXp7NWi/+6ZNRU/MkqISpvp37cHYWdiA1q7Kl3O7DlK55ndWmHaYYv5ehrpxPoPCXmGBWOIq+KOj81Cy6nLxpQ1BWRzIpYpk+puBfkJcOu5cAAmaEHJzWm9EWm0ybA=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: gitea-admin-secret
      namespace: gitea
    type: Opaque

