apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitea-admin-secret
  namespace: gitea
spec:
  encryptedData:
    password: AgBo5JIxD5UM8e77St1K+20zG27JIt9ELEM9Sy7zAeZnbR17b9k9yjpvxEzZbdUjEvqnNYfq7YB6opNRvZZRkTQ0ySgXvB0V1bcnDx0gRG8ogPzIQXh0mAnw6nAoy6OC+XdUIM/ruknmG/b78dOb8JS2if7tWEzw+BBi1VTl5WBtxTlSijnJWBHBWLKjjpTM8nb6qMnMobLy6JYaJFnQEFbJrtrugim3bHXdxmPzKZ1ORhvNh3E9pghGE2qbKszYPm/rDmMFOIaPxxS9dhxcKsQCyE91+UI0aYAuKlgkBMxCIUUDD0Mho0txGX7WNfTUhQv+xujOOr8b7dXgK3pBo04SP+r3NceSmNrymE5LvX74NQhjR3UpvNBt9ypzxO8w6POh3yPiGZp8UacE8hIGCnrM2YKJlW7SVS6ywMyjDPCubJjz3JfkzmfmZUmxfhEVmYxzSEoJb8tpcbO0QhzWDdYABSgo7vm9I/u8W+Jtz8FZC8YWm2BE7jVI1Cs5dmzaD3itlDN9sKQPgXEcn0BZg8W49jOcRz38SPk13NrPvGMhfTSnAtsE0wkYg1JjWJ6OUSDIZOaXswkRyNqheA9en7iG50SMHTxhSd27kxaWSaOr3ARVtzbOGx2PtkQs8wCZtQwkfq0ETXsYPg2WOXQgOI4CMlkLy17k5PrPBYQ9h/41+dBlpI4Do9jg3YJ1GaJc2B8EEoAijfA2++u1bAfh2aRiTviMyUXx39g=
    username: AgAfjKtuRQmVhBWWME0V1BAXHv7gvDTkfd/BrgU+yNONVwocY88N2jSts85LCvk9oJ8FJRJocZj/PVsmdCD0eT55CqNTqzPsFbhxuqlAAo95JRD/TTpVoA5QcegZxThaxuDEiDGdfZPpZxTZJ3cKmd+u/GPYS8no7YbMB4GTxzEDYotMrFlzahzzdzWYETaULp2FM67/DLmJfl/embzkafyYZtGntQpII22onb8QrDmJrtRxuRyi6g1ve50yLDgCnWlMLpKyZE5PorYW40RRHBJQ3B0K7XWyAnM+y8IjIadAFQglHeYHUIp+jc3y/oKoTXIPgn1oaJkMqBbK2xH2sYF0rID+jMExkX23n8OIqZ9v74ZWWmsIFATjjM4rLtI8aqEauxSgIcLRstGmo/pQSajrOrpZlUbrA1uXqLQ7xv8ohBHx+LOlkqOe0hQE+sTp1MELH7IWsx6nd59xseI62lJxMakjiyrVNFw2zYV/G9+6J1Pq11syWi2UKyujRlvnCa2M103sezg+NlurbabPad59AvfsGWlSX09Nd1q4zXNkz2X8i95u0BOXBSgyVOwmzXiL1teaJW6xx6FqFTnFP7a97c4sgATL2CL/nEFhpgdC2bovjulEwJoeAJWcTrltg+C0en3tfItD14i9LCJy1odB4qT1X+TAhyorK1SE3AJxNUN1mmsOO0Vfu9xDxaWXzNRUP05FiTW164c=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: gitea-admin-secret
      namespace: gitea
    type: Opaque

