apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitea-admin-secret
  namespace: gitea
spec:
  encryptedData:
    password: AgCk4S21A3lGpwddcSn6/ru6ML7+efySR4R9cb6YM2hjJEcTwRs9pPzypgvUVsAlC1RywHbpReFP0ANohOsCxt0PGjEfuUQOHbGFDAkZOLiatqxaATiuypyTKUalD4GlOEf+cgt80g3NAvaz/KnE8mJH8pFTKQZbjJ5YJIiQxhW0+r3EYYlOPofor+2XWOsMSL1xta6x7pPH5aOXX6D5rTAuqNKBqqpvDvKnq+tHSDkENkHUb19O5oxtmcjTA+boCv903O28mfPrgCJzoUPOg0CYdCuFpmH6A3blUqbMp96o3soN1Rn5Rm7nN5rAmkBJuiTn20NLvLWTFl2Dl3crMN5ZPIfLLtQw/T2OB0QzDEVSz4hevwrHnapVRaeC4ocIIGCyvJwQA7xVEbW+fwtQBZojZK+JCnWAJkbtUW2ytoleq2UR16CvF0NEzfd2Pv3Q6GdI9/A1OIAm5dZhBrTiJEwnL06Hva8rG1oeh138uOKGTTZSXuhk5wW4H7RTxB3vCgXVPfWaA+hO8klyS7aAnLd620EMyaJPRFy8PNPmx7XC0txievvSp2haLpLK2rHvpgudgdlDPwQb7WpB2nsgBQ6yYNBxzEfyTDGxCqWCBRY0yW4HXyJFDBZ6Ot8RoLSXyiwJ+bldADCpYVGQP/uYB+HrHDPpE5os1HiZ2+6PCkyKCMx6/UUn9uFKk+I2Jw5b18NbaRt+5xM6JDClzyJc/mjEI3AJm4EDoG8=
    username: AgBwoXNul3yybNzymvDdpdcPnRgQiKAgroagOpcRtstXP6ssr8+VHpF69R4mjLUogFooqTBQ/Xhx/uIwjHBEa+hMTV2TC4bwkgkfIDEcGTL2SzsuER+BTMFqa66BuqF4uZzLr40dvv8GhAfvKdgzDkZU9OEm4ANfp4HpH4zhPZdfWyRA0QnvLb3Qmzj8VhtWT+jzg1pDLPWSVZfqnCQuRab7JA13qt7em4CTB+cWKKxLq2XIwtZ+IEfumjNNfwd1y5gQBmvd2J5iF6b6zQGuJ3LggK66HuomvlK29i0QZkWHpcF4e6e9BZPk1CbSTeXyFYj0lZdtsPKSY7BfCyyvWThheMwA/N1Bff2UBAZBSa/TbWYmM2nu2//BMIi8uswD90gxAqA8PLmv9Gayf+eKs619EGeFzpo+jsMUNxYCjG836i1lxnsHqDbrVlSOX65sg9TekwLEFgEJAOm0aNhIirB3cdEfe24tUgjqZPqaUdafNwRh/51aTjPFlwk8ZyMgQUVI8H/2w3NBC+HPzvR/hDK84hHWvq1oIxImLfJyQbetOOP4SdW52l7At+F6v0tckkhGj9hGJ7LoXOXyOw+1XClVE1oeg4Maym75B6Z5TFBUETYi1z8K/yZd2CVSIa4Yh8aMMxQAjADNaQ1lGXgmLQGeLh++ntSsA4i2Zepsd3E1HlRkLpkp4OmdGk2EoKpWFpkqoke8/KFwCBA=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: gitea-admin-secret
      namespace: gitea
    type: Opaque

