apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitea-database-secret
  namespace: gitea
spec:
  encryptedData:
    database: AgCCvaSQa9V6h3qVoIVzIaqU1SKBdygvmSA0qH5jzfM3hrehiu2/DB8V6RufPTaKw3lHb8wn4msCHgBiCodGVJMvICZtbyd+0nHKRl8uTFv1xN41TSzCa9Qbv4KI97M/DPPjp5V9BAO2pJisC83/NVDgkSkN31M9Gr1XXJqIcSru5spBvr2h6mx62Igzk67drM3FYtrsKdm2WVnBbhTYxqj5ZeOS7hrhycy7eGVL5JzJCxCRyWqgbGCZhLq+fTSi101krM18COWSKC6TSm4NGi2L9M5QzaS94ikxZE+VzdGS+Cei7w1vzqmf9ZGTys6ndmIJFdk/uV38IMtMkP8zsR3p8jg8Lyk8fahsGIIIW914tWicVftLMqTonHiKBhwbQJjyzkjVk7IJX42euKxO21MuqVpb9297me2IV3WOagmYpeeUArM9eXfkbH7JyDalgQdN4GhOY0NB221LVg+8w+4bRgFBQvU0HuSVlj3v3dg5ESRH1tJmP3UtjzwmV28qGVKIGQKExZShxTu1G7wiiHVJL87ai8lc6Zf5AAel83pt+NT5ghWwKyde7WiwLPXrvmcfZd/PEVGiOBkZUpSJQIGSjoD/cZMwlouIcZE5TUr3DIqrNwY8eeTTr5z4dPGVFHXa2m3yscOmQvjYqndvuaKrUaYVs5DtOd/w5jSJasw27Kzsf2k3z5qCBx86kfdrvlsH/JUQ7LqcIneRd6RUGdG0hyNlHy4gJcD5cs4+IbPPJSe+ZSEWL6dD3r1mFLMlktItpFGvXHpFXYx5cJcfuVQDjQZXmBbPzsRCzX/iQ+elCiyOXeBREmGFpM23vkx48H1T8duTOQKM2oyypnehLuLqcpE=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: gitea-database-secret
      namespace: gitea
    type: Opaque

