apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitea-admin-secret
  namespace: gitea
spec:
  encryptedData:
    password: AgBrWrYNJFv6tH+q2IeY9W3mKjY4ZXU2+Pp7+2HgA3wX5pF7loFtdAFdx98MclEYPptYH/IHyYd3GjhtubdSo+T2FLS1XEKLMXOD/B+fkGKTXlCWwCazhlVdhnltjR1IPzqS87DQ96xig3muVPwz5eNwyAJcCitEdvVjWGjsnT63AVHxiNtObnNHeoegUOw/nk7Ynh8LeIXFZV4qT+Rq2Rfbs4t969+e8/5kwA3aWNGiWC4QrilM9tQz0cGgIvIDsQS/4rPRo89z5m5aZOYX7DYsHCGx3YSLhtjlWoVBkmE0LAcD8CcsTpxKewEtk+M4jDkst78myyzeXt8XpUMQL2RAoQ/SvA7cDBv7L/qPrEcGXea4Bg9x/NaBd5nFCjMAnsEAbow9Qe5Yva2SlstUNHdLiSq4UGeMjWxukretdk9COlflZerFzCrojXeBX42kSKnmlIaD8drk+iDZyTekpNps7/URNZucQ+AFEvE0wrWyhsSvfm96q5h1SCkrYqnoY35DYq0r3KK2i+fL1npr//YCAzAQGfkJXtu4D+ytHSAUzmqPyicN+egIWQ7bD1xZACs52FQzecHBLO+QfUHvCyc/qrgFe3wL7aYSwavlfuRcVpVjwPe4QGsneqZ+5zgoBShUjIj26go/id3PnE+8OYAW+wtZEER81/m//1aTRIDVgr6RQlqp/85LALfm0GEhbjHzGJLstuYjhWszxKLtcRrKzRssQTBC6K8=
    username: AgAwy6kVzgIjQyDNC0KDaLVaWwxb8nLcZlh0nRUlWtSqkLduaZ78RQaUlBF6WOH/lAhHOLteX3cI0u2FJLn4aNajq5zYQ3VJJ7dDtaRax+BVAiMiHX+wEX5EZkRHfwKsRQpBElifQ0jMQ0D8CgNm0KFMn+DXLk/u6iwDC2Zn9vLHwEB1psIySzM4DHE5tUUQN6/zZr2XpfQ1U2HN5c1l2M7UoMJpbM3V55YOzSIMrEHtZQCNov6uv1MBjdPYcXnUPqOoSU3f1ffMceRUWoC+LJf2bpFJWF5OTk+jvQpWyzbpdpTOVBhOex0XQ+odfIndkhQxfv5h0XvGBslk6E8v3Xg8SA+R6ZE5gAPQwdwY9rD+8zRR+zQO4yW7tW8Vzp4PIbMhcekrPHS1NYXubwKZUF4Bm5h2CirUYo3ywE2dL2af4MyqYJqSj1jeEk+gq7eUTteXbDIbu/1w6M5tgD37CJIzi6cpZBZNQ/KwibpmiQ5+je38yHpe1ROBavGIuOOeSn8+IjJuMfryXwbWrRnO+4FIaYVIMUuYRbLf5yzg2Rz/nhX0MnMOETdMP+4Iwklya15D1CwjjBJhvnmVu6L8Q/BWhm10mKBRp+ps2DKbmkTYXw7e7HvaEpkRbEyb6OPuMnENIuRb569zSTh4eTcekZtBafhctUWeBWsbzelrsbEU/F0ds82YDoK5aCVQxIg0n15JUuQV42sz64I=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: gitea-admin-secret
      namespace: gitea
    type: Opaque

