apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: gitea-database-secret
  namespace: gitea
spec:
  encryptedData:
    database: AgDBKCLHSUOqt1snC/croq/4ApG8DEA19YdyOc+gcR6hhq2zfdiEa1IhSemk6oiGpv3kywXQk1OaEY/0oT8W+0Lgb1WclX0rTBZRnUHiqWm0Z9TP2p5YiOA0v+6uwQBDHQulbvX66GvSEAxaEHhFKWoue3UCu+ZT8ms3i/hSdHzmJEH4eQ6Vpep1MVul+NkzmbAEaAgH0oqxgBqlz0iKJLIPT6yYjE449Q62e/8x+9HbeoQLvTXkI/fRuUQkGUkT86z38ah+JYeET2PwQOmKNlesy0dN78TApUkik3C5T0mlDzk9IxS2RtiS/Gcb4718LBnLLgi6qjVuaXtMO6B/FXc8hGo6OGjSbarwojH/c4K5vx593Wo0NEsK2eKvgDpzkIyJVFZhXauMVbM87QVW+CJxqgjz85/nFhndzPylFVbMGKC1SEiqpXeofYQL/kpWSWIdoEpQ5HO79Xw8E7Jwgu/MMgLBwF5A7qzbsHqj37G1VPT/z+NlIy3Wi89LPNm2hRsB984n041PSf2kShHP7c4xgogbdgj121VDHw9TdSCQ8/ygTuO3Fk9z44sipynkVWV5/T2M4nY50i3vveTVIXPt5FXBgmJMKYm0L0WYbAOicHzsC+vtWCB0woYswbVSTOXKGIUrNsvwTfon1AdSftD+a4DR9g6j27Erohk0CON3u6X7arzLSfD3yZ2j9+bYGVO2qLBMaej5xO8n4NeLZw9emeCCU9fGOOqr2K9j4bMNabuxXGTNqagV7ZyfYg9zZCFTNma99g6AiSbJAAF/EU8ONOxvGPkU3O74fnf385oV66diTTeibUS/6tV82bcGwo8cRehZxtMNzGk//6zbYdO+7OUKrUlP
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: gitea-database-secret
      namespace: gitea
    type: Opaque

