apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mysql-credential-files-secret
  namespace: database
spec:
  encryptedData:
    root-password: AgBbXEoAhXhF5vdxpv4X3UdFkkdES5I4poXpEYgMa4Q9pE2SIsXvFubYDqPuSK8IQwyGNQjiEHyI7ikOBHUJ7bkzPvz0KIicEcWBizr28pznj51nJ38hA+6PGDg1L8JKANRhwLtcI/+/Mu/uQc3HQQs7QifwQfVxiOt/rJ5uNS65DSEdYJJYijPIBwn0b7OwEM2GlmkIiVqP8ESIlVKauGN48RT2IZTAU1wuQnOmU22ljUTbe98BsRgixra/etOAE5LT4SGXdZNflZwC3dtM4sMQxeZVoMrbZm0bUaHuSlRSb/Zp/7XxyQnS0S/yGHYN2e+KUsYqGFs2DxVw8lzxEBWqpBTqNIUg3gA92zm7X/qwOc7tFrB1TUH2o9u/s4sFA0q+mKyF6NlvFFasAsrRMr+mk1Zs6TEAdyRIOqeaZlpzR1sOXtETTfAx9Cis+gTcy8tPENr5TfRjai236ngJORYGnfH4hfqIiFYpQ6lcrg5XWxOmfSd8IO8jLiLPtmFRkE5aTZBwmvRjFhOOI5GaGQBs0UoFTZjOM9OVbQGZh5HmdNVlIDeYNA04T2486Dkf0pzOlpvfLhOI8DSMilLNGmnAa/vpfbNye0Lhji7PLJHtkBgcMEmuvZBPkFxZ0oiS6AgTdfiQctbpqpSBueA6MEIUMylM+1nQG/f2IQNHnQseTKaRVDo/duoeGg/z1rMjE0kCUgylymcShCHrQCM79UGyAenwa991+pM=
  template:
    data: null
    metadata:
      creationTimestamp: null
      name: mysql-credential-files-secret
      namespace: database
    type: Opaque

