apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gitea
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://dl.gitea.io/charts'
    targetRevision: 5.0.4
    helm:
      values: |-
          gitea:
            config:
              server:
                ROOT_URL: "http://apps.gensokyo-cluster.lan"
            #additionalConfigSources:
            #- secret:
            #    secretName: gitea-database-env-secret
            service:
              DISABLE_REGISTRATION: true
            admin:
              existingSecret: gitea-admin-secret
          persistence:
            enabled: true
            storageClass: gensokyo-mayastor-singleton
          service:
            http:
              type: LoadBalancer
              clusterIP:
              annotations:
                metallb.universe.tf/allow-shared-ip: gitea-ip
            ssh:
              type: LoadBalancer
              clusterIP:
              annotations:
                metallb.universe.tf/allow-shared-ip: gitea-ip
          ingress:
            enabled: true
            annotations:
              name: gitea
            className: nginx
            hosts:
            - host: gitea.apps.gensokyo-cluster.lan
              paths:
              - path: /
                pathType: Prefix
          postgresql:
            enabled: false
          mysql:
            enabled: true
    chart: gitea
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: gitea
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
    syncOptions:
    - CreateNamespace=true

