---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: navidrome
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://k8s-at-home.com/charts/'
    targetRevision: 6.2.0
    helm:
      values: |-
        env:
          ND_IMAGECACHESIZE: "1GB"
          ND_MUSICFOLDER: "/music/library"
          ND_BASEURL: "/music"
        persistence:
          config:
            enabled: true
            size: 16Gi
            storageClass: gensokyo-mayastor-singleton
          music:
            enabled: true
            type: custom
            volumeSpec:
              nfs:
                server: 10.0.1.9
                path: /rust1/media/music
        ingress:
          main:
            enabled: true
            ingressClassName: nginx
            annotations:
              cert-manager.io/cluster-issuer: letsencrypt-production
              nginx.ingress.kubernetes.io/configuration-snippet: |
                proxy_cache images-cache;
                proxy_cache_valid any 60m;
                proxy_cache_revalidate on;
            tls:
            - hosts:
              - apps.trash-hosting.com
              secretName: app-cert
            hosts:
            - host: apps.trash-hosting.com
              paths:
              - path: /music
                pathType: Prefix
                service:
                  port: 4533
    chart: navidrome
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: applications
  syncPolicy:
    automated:
      prune: true
    syncOptions:
    - CreateNamespace=true
