---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: gensokyo-mayastor-singleton
parameters:
  repl: '1'
  protocol: 'nvmf'
  ioTimeout: '30'
  local: 'true'
provisioner: io.openebs.csi-mayastor
volumeBindingMode: WaitForFirstConsumer
