---
apiVersion: v1
kind: Namespace
metadata:
  name: diun
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: diun-config-pvc
  namespace: diun
spec:
  storageClassName: gensokyo-mayastor-singleton
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: diun
  name: diun
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: diun
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - watch
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: diun
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: diun
subjects:
- kind: ServiceAccount
  name: diun
  namespace: diun
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: diun-allow-all
  namespace: diun
spec:
  podSelector: {}
  ingress:
  - {}
  egress:
  - {}
  policyTypes:
  - Ingress
  - Egress
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: diun
  name: diun
spec:
  replicas: 1
  selector:
    matchLabels:
      app: diun
  template:
    metadata:
      labels:
        app: diun
      annotations:
        diun.enable: "true"
    spec:
      securityContext:
        fsGroupChangePolicy: "Always"
        fsGroup: 100000
      serviceAccountName: diun
      containers:
      - name: diun
        image: crazymax/diun:4.21
        imagePullPolicy: Always
        securityContext:
          runAsUser: 100000
          runAsGroup: 100000
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
        args: ["serve"]
        resources:
          limits:
            cpu: "200m"
            memory: "64Mi"
            ephemeral-storage: "128Mi"
          requests:
            cpu: "200m"
            memory: "64Mi"
            ephemeral-storage: "64Mi"
        envFrom:
        - secretRef:
            name: diun
        env:
        - name: TZ
          value: "Australia/Sydney"
        - name: LOG_LEVEL
          value: "info"
        - name: LOG_JSON
          value: "false"
        - name: DIUN_WATCH_WORKERS
          value: "20"
        - name: DIUN_WATCH_SCHEDULE
          value: "0 */6 * * *"
        - name: DIUN_PROVIDERS_KUBERNETES
          value: "true"
        - name: DIUN_PROVIDERS_KUBERNETES_WATCHBYDEFAULT
          value: "true"
        volumeMounts:
        - mountPath: "/data"
          name: "data"
      restartPolicy: Always
      volumes:
      - name: "data"
        persistentVolumeClaim:
          claimName: diun-config-pvc
