apiVersion: v1
kind: Namespace
metadata:
  name: diun
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: diun-config-pvc
  namespace: diun
spec:
  storageClassName: gensokyo-mayastor-singleton
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: diun
  name: diun
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: diun
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - watch
  - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: diun
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: diun
subjects:
- kind: ServiceAccount
  name: diun
  namespace: diun

---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: diun
  name: diun
spec:
  replicas: 1
  selector:
    matchLabels:
      app: diun
  template:
    metadata:
      labels:
        app: diun
      annotations:
        diun.enable: "true"
    spec:
      serviceAccountName: diun
      containers:
        - name: diun
          image: crazymax/diun:latest
          imagePullPolicy: Always
          args: ["serve"]
          envFrom:
          - secretRef:
              name: diun
          env:
          - name: TZ
            value: "Australia/Sydney"
          - name: LOG_LEVEL
            value: "info"
          - name: LOG_JSON
            value: "false"
          - name: DIUN_WATCH_WORKERS
            value: "20"
          - name: DIUN_WATCH_SCHEDULE
            value: "0 */6 * * *"
          - name: DIUN_PROVIDERS_KUBERNETES
            value: "true"
          - name: DIUN_PROVIDERS_KUBERNETES_WATCHBYDEFAULT
            value: "true"
          - name: DIUN_NOTIF_DISCORD_WEBHOOKURL
            value: "https://discord.com/api/webhooks/959232942054469673/N5zE4rW1CHeTYk2b4QgtkI5J5xrXwfLgdt2sJDgCC1hD-otyVh5bHoWMJDGTlWkgagHg"
          volumeMounts:
          - mountPath: "/data"
            name: "data"
      restartPolicy: Always
      volumes:
      - name: "data"
        persistentVolumeClaim:
          claimName: diun-config-pvc

